export const products = [
  {
    id: 1,
    name: 'Fluted Pillar Candle - 12 cm',
    description:
      'Our 12 cm Fluted Pillar Candle features an elegant ribbed design that creates beautiful light patterns when lit. Each candle is hand-poured using premium wax for a clean, long-lasting burn. The soft pink color adds a touch of warmth and sophistication to any space.',
    price: 150.0,
    images: [
      '/pink-fluted-candle.jpeg',
      '/small-pink-candles.jpeg',
      '/candle-with-vase.jpeg',
    ],
    details: [
      'Hand-poured premium wax',
      '30-hour burn time',
      'Cotton wick',
      'Elegant fluted design',
      '12 cm height',
    ],
    scent: 'Unscented',
    size: '12 cm',
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 552,
    category: 'bestseller',
    related: [2, 5, 7],
  },
  // {
  //   id: 2,
  //   name: 'Fluted Pillar Candle - 6 cm',
  //   description:
  //     'The 6 cm Fluted Pillar Candle is perfect for creating intimate lighting arrangements or as part of a larger candle display. Despite its smaller size, it features the same elegant ribbed design and premium quality as our larger candles.',
  //   price: 100.0,
  //   images: [
  //     '/small-pink-candles.jpeg',
  //     '/pink-fluted-candle.jpeg',
  //     '/lavender-candle.jpeg',
  //   ],
  //   details: [
  //     'Hand-poured premium wax',
  //     '15-hour burn time',
  //     'Cotton wick',
  //     'Elegant fluted design',
  //     '6 cm height',
  //   ],
  //   scent: 'Unscented',
  //   size: '6 cm',
  //   boxWidthInCm: 14,
  //   boxHeightInCm: 5,
  //   boxWeightInGrams: 295,
  //   category: 'bestseller',
  //   related: [1, 5, 7],
  // },
  // {
  //   id: 3,
  //   name: 'Fluted Pillar Candle - 26 cm',
  //   description:
  //     'Make a statement with our 26 cm Fluted Pillar Candle. This larger size creates a dramatic focal point for special occasions or as a centerpiece. The beautiful purple hue and ribbed texture add sophistication to any setting.',
  //   price: 220.0,
  //   images: [
  //     '/purple-candle-set.jpeg',
  //     '/candle-with-vase.jpeg',
  //     '/pink-fluted-candle.jpeg',
  //   ],
  //   details: [
  //     'Hand-poured premium wax',
  //     '60-hour burn time',
  //     'Cotton wick',
  //     'Elegant fluted design',
  //     '26 cm height',
  //   ],
  //   scent: 'Unscented',
  //   size: '26 cm',
  //   category: 'new',
  //   related: [1, 4, 7],
  //   boxWidthInCm: 26,
  //   boxHeightInCm: 26,
  //   boxWeightInGrams: 717,
  // },
  {
    id: 4,
    name: 'Fluted Pillar Candle - 30 cm',
    description:
      'Our largest fluted candle stands at an impressive 30 cm tall, creating a stunning visual impact. The sage green color brings a touch of nature indoors, while the ribbed texture creates beautiful light patterns when lit.',
    price: 280.0,
    images: [
      '/green-candles.jpeg',
      '/purple-candle-set.jpeg',
      '/pink-fluted-candle.jpeg',
    ],
    details: [
      'Hand-poured premium wax',
      '80-hour burn time',
      'Cotton wick',
      'Elegant fluted design',
      '30 cm height',
    ],
    scent: 'Unscented',
    size: '30 cm',
    category: 'new',
    related: [3, 6, 7],
    boxWidthInCm: 30,
    boxHeightInCm: 30,
    boxWeightInGrams: 901,
  },
  {
    id: 5,
    name: 'Premium Fluted Candle - 6 cm',
    description:
      'Our Premium 6 cm Fluted Candle is crafted with a luxury wax blend for an even longer, cleaner burn. The lavender color and elegant ribbed design make it perfect for creating a calming atmosphere.',
    price: 160.0,
    images: [
      '/lavender-candle.jpeg',
      '/small-pink-candles.jpeg',
      '/candle-with-vase.jpeg',
    ],
    details: [
      'Hand-poured luxury wax blend',
      '20-hour burn time',
      'Premium cotton wick',
      'Elegant fluted design',
      '6 cm height',
    ],
    scent: 'Unscented',
    size: '6 cm',
    category: 'bestseller',
    related: [1, 2, 7],
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 295,
  },
  {
    id: 6,
    name: 'Pumpkin Shaped Candle',
    description:
      'Add a seasonal touch to your home with our Pumpkin Shaped Candle. This unique design brings warmth and charm to autumn decor, with the same premium quality you expect from Umi Candles.',
    price: 80.0,
    images: [
      '/pumpkin-candle.jpeg',
      '/green-candles.jpeg',
      '/pink-fluted-candle.jpeg',
    ],
    details: [
      'Hand-poured premium wax',
      '25-hour burn time',
      'Cotton wick',
      'Unique pumpkin design',
      '8 cm height',
    ],
    scent: 'Unscented',
    size: '8 cm',
    category: 'new',
    related: [1, 4, 7],
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 295,
  },
  {
    id: 7,
    name: 'Combo Set - 12 cm & 26 cm',
    description:
      'Our most popular combination, this set pairs a 12 cm and 26 cm fluted candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 160.0,
    images: [
      '/candle-with-vase.jpeg',
      '/purple-candle-set.jpeg',
      '/pink-fluted-candle.jpeg',
    ],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '12 cm & 26 cm',
    category: 'bestseller',
    related: [1, 3, 5],
    boxWidthInCm: 26 + 12,
    boxHeightInCm: 26 + 12,
    boxWeightInGrams: 552 + 717,
  },
  {
    id: 8,
    name: 'Pair of 30cm Toothed Ribbed Pillar',
    description:
      'Our most popular combination, this set pairs of 30 cm Toothed Ribbed Pillar candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 300.0,
    images: ['/toothed-set.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '30 cm & 30 cm',
    category: 'extravagant',
    related: [1, 3, 5],
    boxWidthInCm: 26 + 12,
    boxHeightInCm: 26 + 12,
    boxWeightInGrams: 552 + 717,
  },
  {
    id: 9,
    name: 'Ribbed Pillar Candles 3 set combo',
    description:
      'Our most popular combination, this set pairs of 30 cm Toothed Ribbed Pillar candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 280.0,
    images: ['/ribbed-set.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '30 cm, 26cm & 12cm',
    category: 'extravagant',
    related: [1, 3, 5],
    boxWidthInCm: 26 + 12 + 30,
    boxHeightInCm: 26 + 12 + 30,
    boxWeightInGrams: 552 + 717 + 901,
  },
  {
    id: 10,
    name: 'Column Ribbed Pillar',
    description:
      'Our most popular combination, this set pairs of 30 cm Toothed Ribbed Pillar candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 30,
    images: ['/column-ribbed-pillar.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '30 cm',
    category: 'extravagant',
    related: [1, 3, 5],
    boxWidthInCm: 30,
    boxHeightInCm: 30,
    boxWeightInGrams: 901,
  },
  {
    id: 11,
    name: 'Wedding and Party Gift: 12 cm Ribbed Pillar',
    description:
      'Our most popular combination, this set pairs of 30 cm Toothed Ribbed Pillar candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 100,
    images: ['/wedding-gift.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '30 cm',
    category: 'extravagant',
    related: [1, 3, 5],
    boxWidthInCm: 12,
    boxHeightInCm: 12,
    boxWeightInGrams: 552,
  },
  {
    id: 12,
    name: 'Candle oil burner and fragrance oil set',
    description:
      'Our most popular combination, this set pairs of 30 cm Toothed Ribbed Pillar candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 200,
    images: ['/candle-oil-set.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '30 cm',
    category: 'extravagant',
    related: [1, 3, 5],
    boxWidthInCm: 12,
    boxHeightInCm: 12,
    boxWeightInGrams: 552,
  },
];
