export const products = [
  {
    id: 1,
    name: 'Fluted Pillar Candle - 12 cm',
    description:
      'Our 12 cm Fluted Pillar Candle features an elegant ribbed design that creates beautiful light patterns when lit. Each candle is hand-poured using premium wax for a clean, long-lasting burn. The soft pink color adds a touch of warmth and sophistication to any space.',
    price: 150.0,
    images: ['/pink-fluted-candle.jpeg'],
    details: [
      'Hand-poured premium wax',
      '30-hour burn time',
      'Cotton wick',
      'Elegant fluted design',
      '12 cm height',
    ],
    scent: 'Unscented',
    size: '12 cm',
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 552,
    category: 'bestseller',
    related: [2, 5, 7],
  },
  {
    id: 4,
    name: 'Fluted Pillar Set 12 & 26cm',
    description:
      'Our large fluted candle stands at an impressive 26 cm tall, creating a stunning visual impact. The sage green color brings a touch of nature indoors, while the ribbed texture creates beautiful light patterns when lit.',
    price: 280.0,
    images: ['/green-candles.jpeg'],
    details: [
      'Hand-poured premium wax',
      '80-hour burn time',
      'Cotton wick',
      'Elegant fluted design',
      '30 cm height',
    ],
    scent: 'Unscented',
    size: '30 cm',
    category: 'new',
    related: [3, 6, 7],
    boxWidthInCm: 30,
    boxHeightInCm: 30,
    boxWeightInGrams: 901,
  },
  {
    id: 5,
    name: 'Premium Fluted Candle - 6 cm',
    description:
      'Our Premium 6 cm Fluted Candle is crafted with a luxury wax blend for an even longer, cleaner burn. The lavender color and elegant ribbed design make it perfect for creating a calming atmosphere.',
    price: 160.0,
    images: ['/lavender-candle.jpeg'],
    details: [
      'Hand-poured luxury wax blend',
      '20-hour burn time',
      'Premium cotton wick',
      'Elegant fluted design',
      '6 cm height',
    ],
    scent: 'Unscented',
    size: '6 cm',
    category: 'bestseller',
    related: [1, 2, 7],
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 295,
  },
  {
    id: 6,
    name: 'Pumpkin Shaped Candle 6cm',
    description:
      'Add a seasonal touch to your home with our Pumpkin Shaped Candle. This unique design brings warmth and charm to autumn decor, with the same premium quality you expect from Umi Candles.',
    price: 80.0,
    images: ['/pumpkin-candle.jpeg'],
    details: [
      'Hand-poured premium wax',
      '25-hour burn time',
      'Cotton wick',
      'Unique pumpkin design',
      '8 cm height',
    ],
    scent: 'Unscented',
    size: '8 cm',
    category: 'new',
    related: [1, 4, 7],
    boxWidthInCm: 14,
    boxHeightInCm: 5,
    boxWeightInGrams: 295,
  },
  {
    id: 7,
    name: 'Combo Set - 12 cm',
    description:
      'Our most popular combination, this set pairs two 12 cm fluted candle for a beautiful coordinated look. Perfect for creating visual interest on mantels, dining tables, or as a thoughtful gift.',
    price: 160.0,
    images: [
      '/candle-with-vase.jpeg',
      '/purple-candle-set.jpeg',
      '/pink-fluted-candle.jpeg',
    ],
    details: [
      'Hand-poured premium wax',
      'Two complementary candles',
      'Cotton wicks',
      'Elegant fluted design',
      '12 cm and 26 cm heights',
      'Special gift packaging',
    ],
    scent: 'Unscented',
    size: '12 cm & 26 cm',
    category: 'bestseller',
    related: [1, 3, 5],
    boxWidthInCm: 26 + 12,
    boxHeightInCm: 26 + 12,
    boxWeightInGrams: 552 + 717,
  },
  {
    id: 8,
    name: 'Pair of 30cm Toothed Ribbed Pillar',
    description:
      'This elegant pair of 30cm toothed ribbed pillar candles creates a dramatic statement piece for any room. The distinctive toothed ribbing catches and reflects light beautifully, while the substantial height makes them perfect for formal dining or special occasions.',
    price: 300.0,
    images: ['/toothed-set.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Two matching 30cm candles',
      'Cotton wicks',
      'Distinctive toothed ribbed design',
      '30 cm height each',
      'Elegant presentation box',
    ],
    scent: 'Unscented',
    size: '30 cm (pair)',
    category: 'extravagant',
    related: [4, 9, 10],
    boxWidthInCm: 32,
    boxHeightInCm: 32,
    boxWeightInGrams: 1802,
  },
  {
    id: 9,
    name: 'Ribbed Pillar Candles 3 set combo',
    description:
      'Create a stunning tiered display with this three-piece ribbed pillar candle set. Featuring candles in 30cm, 26cm, and 12cm heights, this collection allows you to create beautiful layered arrangements that add depth and elegance to any space.',
    price: 280.0,
    images: ['/ribbed-set.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Three graduated heights',
      'Cotton wicks',
      'Classic ribbed design',
      '30cm, 26cm & 12cm heights',
      'Coordinated color palette',
    ],
    scent: 'Unscented',
    size: '30cm, 26cm & 12cm',
    category: 'extravagant',
    related: [1, 4, 7],
    boxWidthInCm: 68,
    boxHeightInCm: 68,
    boxWeightInGrams: 2170,
  },
  {
    id: 10,
    name: 'Column Ribbed Pillar',
    description:
      'Our Column Ribbed Pillar candle combines classic architectural inspiration with modern candle-making craftsmanship. The vertical ribbing creates elegant shadows and adds textural interest, making it a perfect standalone statement piece or part of a larger arrangement.',
    price: 30,
    images: ['/column-ribbed-pillar.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Architectural column design',
      'Cotton wick',
      'Vertical ribbed texture',
      'Compact size for versatile placement',
      'Clean burning formula',
    ],
    scent: 'Unscented',
    size: '15 cm',
    category: 'extravagant',
    related: [1, 4, 8],
    boxWidthInCm: 16,
    boxHeightInCm: 16,
    boxWeightInGrams: 450,
  },
  {
    id: 11,
    name: 'Wedding and Party Gift: 12 cm Ribbed Pillar',
    description:
      'Perfect for weddings, parties, and special celebrations, this 12cm ribbed pillar candle comes beautifully packaged as a gift. The elegant ribbed design and premium quality make it an ideal favor or centerpiece element that guests will treasure long after your event.',
    price: 100,
    images: ['/wedding-gift.jpeg'],
    details: [
      'Hand-poured premium wax',
      'Gift-ready packaging',
      'Cotton wick',
      'Elegant ribbed design',
      '12 cm height',
      'Perfect for wedding favors',
    ],
    scent: 'Unscented',
    size: '12 cm',
    category: 'extravagant',
    related: [1, 5, 7],
    boxWidthInCm: 14,
    boxHeightInCm: 14,
    boxWeightInGrams: 552,
  },
  {
    id: 12,
    name: 'Candle oil burner and fragrance oil set',
    description:
      'Transform your space with this complete aromatherapy set featuring a beautifully crafted oil burner and premium fragrance oils. The ceramic burner is designed to safely diffuse your favorite scents, while the included fragrance oils provide hours of delightful ambiance.',
    price: 200,
    images: ['/candle-oil-set.jpeg'],
    details: [
      'Ceramic oil burner',
      'Premium fragrance oil collection',
      'Tea light candle included',
      'Easy-to-clean design',
      'Multiple scent options',
      'Complete aromatherapy experience',
    ],
    scent: 'Multiple fragrance oils included',
    size: 'Oil burner + oils',
    category: 'extravagant',
    related: [1, 5, 6],
    boxWidthInCm: 20,
    boxHeightInCm: 15,
    boxWeightInGrams: 800,
  },
];
